// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: runner/proto/runner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareForEvalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PrepareForEvalRequest) Reset() {
	*x = PrepareForEvalRequest{}
	mi := &file_runner_proto_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareForEvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareForEvalRequest) ProtoMessage() {}

func (x *PrepareForEvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareForEvalRequest.ProtoReflect.Descriptor instead.
func (*PrepareForEvalRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{0}
}

type PrepareForEvalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PrepareForEvalResponse) Reset() {
	*x = PrepareForEvalResponse{}
	mi := &file_runner_proto_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareForEvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareForEvalResponse) ProtoMessage() {}

func (x *PrepareForEvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareForEvalResponse.ProtoReflect.Descriptor instead.
func (*PrepareForEvalResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareForEvalResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_runner_proto_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{2}
}

var File_runner_proto_runner_proto protoreflect.FileDescriptor

var file_runner_proto_runner_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x46, 0x6f, 0x72,
	0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x16, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x46, 0x6f, 0x72, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x32, 0x57, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x4d,
	0x0a, 0x0e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x46, 0x6f, 0x72, 0x45, 0x76, 0x61, 0x6c,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x46, 0x6f, 0x72, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x46, 0x6f,
	0x72, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runner_proto_runner_proto_rawDescOnce sync.Once
	file_runner_proto_runner_proto_rawDescData = file_runner_proto_runner_proto_rawDesc
)

func file_runner_proto_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_runner_proto_rawDescData = protoimpl.X.CompressGZIP(file_runner_proto_runner_proto_rawDescData)
	})
	return file_runner_proto_runner_proto_rawDescData
}

var file_runner_proto_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_runner_proto_runner_proto_goTypes = []any{
	(*PrepareForEvalRequest)(nil),  // 0: proto.PrepareForEvalRequest
	(*PrepareForEvalResponse)(nil), // 1: proto.PrepareForEvalResponse
	(*Empty)(nil),                  // 2: proto.Empty
}
var file_runner_proto_runner_proto_depIdxs = []int32{
	0, // 0: proto.Runner.PrepareForEval:input_type -> proto.PrepareForEvalRequest
	1, // 1: proto.Runner.PrepareForEval:output_type -> proto.PrepareForEvalResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runner_proto_runner_proto_init() }
func file_runner_proto_runner_proto_init() {
	if File_runner_proto_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runner_proto_runner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_proto_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_runner_proto_depIdxs,
		MessageInfos:      file_runner_proto_runner_proto_msgTypes,
	}.Build()
	File_runner_proto_runner_proto = out.File
	file_runner_proto_runner_proto_rawDesc = nil
	file_runner_proto_runner_proto_goTypes = nil
	file_runner_proto_runner_proto_depIdxs = nil
}
